platform :ios, '8.0'

def pods
  pod 'AFNetworking'
  pod 'mob_smssdk'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'CNPPopupController'
  pod 'AMap3DMap' #3D地图SDK
  pod 'AMapLocation'
  pod 'AMapSearch'
  pod 'AliyunOSSiOS'
end

target 'KKDoc' do
  pods
end


target 'KKPat' do
  pods
end
